### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by NAThompson** [xuhongzuo/DeepOD#42]
To reproduce:

```cpp
#!/usr/bin/env python3
import numpy
from deepod.models.time_series.dif import DeepIsolationForestTS

arr = numpy.empty(shape=(3, 3))
arr.fill(1.0)

dif = DeepIsolationForestTS(device=None)
dif.fit(arr)
```

Error message:

```
Traceback (most recent call last):
  File "reproduce.py", line 10, in <module>
    dif.fit(arr)
  File "$VIRTUAL_ENV/lib/python3.9/site-packages/deepod/models/time_series/dif.py", line 74, in fit
    self.n_samples, self.n_features = X_seqs.shape[0], X_seqs.shape[2]
IndexError: tuple index out of range
```

I have a workaround:

```
dif = DeepIsolationForestTS(device=None, seq_len=min(100, arr.shape[0])
```

which suggests the fix.

**Comment by xuhongzuo** [comment]
Hi @NAThompson,

A sliding window is used to preprocess time series data, which can produce a set of subsequences for the training of deep learning methods. 

Yes, you suggest a fantastic way to check the input and the default set of `seq_len`. 

I will fix this issue. I really appreciate it.
