### ISSUE TITLE
Are there any restrictions on test data?

### ISSUE THREAD

**Issue by RDADADA** [xuhongzuo/DeepOD#58]
I use DeepSADTS to train. My training data is 8,000. When I tested, I wanted to use single row data to make predictions but an error occurred.
I found that at least 100 rows of data are required for testing. Is there any limit on the number of pieces of test data?
Please help me answer it, thank you

The following is the error message

Traceback (most recent call last):
  File "/home/chris/PycharmProjects/pythonProject/numops/DeepOD/LSTM.py", line 55, in <module>
    scores = clf.decision_function(df_test)
  File "/home/chris/PycharmProjects/pythonProject/numops/DeepOD/deepod/core/base_model.py", line 326, in decision_function
    z, scores = self._inference()
  File "/home/chris/PycharmProjects/pythonProject/numops/DeepOD/deepod/core/base_model.py", line 478, in _inference
    z = torch.cat(z_lst).data.cpu().numpy()
RuntimeError: torch.cat(): expected a non-empty list of Tensors

**Comment by xuhongzuo** [comment]
You are using anomaly detection for time series data. These anomaly detectors use a sliding window to split the whole data into sub-sequences for training and inference. Each individual data sample in time series anomaly detection should be a series of data points. You can use `seq_len` to set this length. 

Thanks for raising this issue.

**Comment by RDADADA** [comment]
Thank you for your explanation~
